<?php

namespace _PhpScoper6af4d594edb1;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit5055f4f44aecce99620f0d2a653e8ec6
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('Composer\\Autoload\\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('_PhpScoper6af4d594edb1\\ComposerAutoloaderInit5055f4f44aecce99620f0d2a653e8ec6', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \_PhpScoper6af4d594edb1\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('ComposerAutoloaderInit5055f4f44aecce99620f0d2a653e8ec6', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\_PhpScoper6af4d594edb1\Composer\Autoload\ComposerStaticInit5055f4f44aecce99620f0d2a653e8ec6::getInitializer($loader));
        $loader->register(\true);
        $includeFiles = \_PhpScoper6af4d594edb1\Composer\Autoload\ComposerStaticInit5055f4f44aecce99620f0d2a653e8ec6::$files;
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire5055f4f44aecce99620f0d2a653e8ec6($fileIdentifier, $file);
        }
        return $loader;
    }
}
// autoload_real.php @generated by Composer
\class_alias('_PhpScoper6af4d594edb1\\ComposerAutoloaderInit5055f4f44aecce99620f0d2a653e8ec6', 'ComposerAutoloaderInit5055f4f44aecce99620f0d2a653e8ec6', \false);
/**
 * @param string $fileIdentifier
 * @param string $file
 * @return void
 */
function composerRequire5055f4f44aecce99620f0d2a653e8ec6($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
        require $file;
    }
}
